CC = gcc
CCO = g++

SOURCES_LIBAGG = \
	libAgg/agg_arc.cpp \
	libAgg/agg_arrowhead.cpp \
	libAgg/agg_bezier_arc.cpp \
	libAgg/agg_bspline.cpp \
	libAgg/agg_curves.cpp \
	libAgg/agg_embedded_raster_fonts.cpp \
	libAgg/agg_gsv_text.cpp \
	libAgg/agg_image_filters.cpp \
	libAgg/agg_line_aa_basics.cpp \
	libAgg/agg_line_profile_aa.cpp \
	libAgg/agg_rounded_rect.cpp \
	libAgg/agg_sqrt_tables.cpp \
	libAgg/agg_trans_affine.cpp \
	libAgg/agg_trans_double_path.cpp \
	libAgg/agg_trans_single_path.cpp \
	libAgg/agg_trans_warp_magnifier.cpp \
	libAgg/agg_vcgen_bspline.cpp \
	libAgg/agg_vcgen_contour.cpp \
	libAgg/agg_vcgen_dash.cpp \
	libAgg/agg_vcgen_markers_term.cpp \
	libAgg/agg_vcgen_smooth_poly1.cpp \
	libAgg/agg_vcgen_stroke.cpp \
	libAgg/agg_vpgen_clip_polygon.cpp \
	libAgg/agg_vpgen_clip_polyline.cpp \
	libAgg/agg_vpgen_segmentator.cpp

SOURCES_LIBAGGFREETYPE = \
	libAggFreetype/agg_font_freetype.cpp \
	libAggFreetype/agg_font_freetype.h

OBJECTS_LIBAGGFREETYPE = \
	agg_font_freetype.o

SOURCES_LIBFREETYPE = \
	libFreetype/base/basepic.c \
	libFreetype/base/ftadvanc.c \
	libFreetype/base/ftapi.c \
	libFreetype/base/ftbase.c \
	libFreetype/base/ftbbox.c \
	libFreetype/base/ftbdf.c \
	libFreetype/base/ftbitmap.c \
	libFreetype/base/ftcalc.c \
	libFreetype/base/ftcid.c \
	libFreetype/base/ftdbgmem.c \
	libFreetype/base/ftdebug.c \
	libFreetype/base/ftfstype.c \
	libFreetype/base/ftgasp.c \
	libFreetype/base/ftgloadr.c \
	libFreetype/base/ftglyph.c \
	libFreetype/base/ftgxval.c \
	libFreetype/base/ftinit.c \
	libFreetype/base/ftlcdfil.c \
	libFreetype/base/ftmm.c \
	libFreetype/base/ftobjs.c \
	libFreetype/base/ftotval.c \
	libFreetype/base/ftoutln.c \
	libFreetype/base/ftpatent.c \
	libFreetype/base/ftpfr.c \
	libFreetype/base/ftpic.c \
	libFreetype/base/ftrfork.c \
	libFreetype/base/ftsnames.c \
	libFreetype/base/ftstream.c \
	libFreetype/base/ftstroke.c \
	libFreetype/base/ftsynth.c \
	libFreetype/base/ftsystem.c \
	libFreetype/base/fttrigon.c \
	libFreetype/base/fttype1.c \
	libFreetype/base/ftutil.c \
	libFreetype/base/ftwinfnt.c \
	libFreetype/truetype/truetype.c \
	libFreetype/truetype/ttdriver.c \
	libFreetype/truetype/ttgload.c \
	libFreetype/truetype/ttgxvar.c \
	libFreetype/truetype/ttinterp.c \
	libFreetype/truetype/ttobjs.c \
	libFreetype/truetype/ttpic.c \
	libFreetype/truetype/ttpload.c \
	libFreetype/raster/ftraster.c \
	libFreetype/raster/ftrend1.c \
	libFreetype/raster/raster.c \
	libFreetype/raster/rastpic.c \

OBJECTS_LIBFREETYPE = \
	basepic.o \
	ftadvanc.o \
	#ftbase.o \
	ftapi.o \
	ftbbox.o \
	ftbdf.o \
	ftbitmap.o \
	ftcalc.o \
	ftcid.o \
	ftdbgmem.o \
	ftdebug.o \
	ftfstype.o \
	ftgasp.o \
	ftgloadr.o \
	ftglyph.o \
	ftgxval.o \
	ftinit.o \
	ftlcdfil.o \
	ftmm.o \
	ftobjs.o \
	ftotval.o \
	ftoutln.o \
	ftpatent.o \
	ftpfr.o \
	ftpic.o \
	ftrfork.o \
	ftsnames.o \
	ftstream.o \
	ftstroke.o \
	ftsynth.o \
	ftsystem.o \
	fttrigon.o \
	fttype1.o \
	ftutil.o \
	ftwinfnt.o \
	truetype.o \
	ttdriver.o \
	ttgload.o \
	ttgxvar.o \
	ttinterp.o \
	ttobjs.o \
	ttpic.o \
	ttpload.o \
	ftraster.o \
	ftrend1.o \
	raster.o \
	rastpic.o

OBJECTS_LIBFREETYPE2 = \
	ftapi.o \
	ftbase.o \
	ftbbox.o \
	ftbdf.o \
	ftbitmap.o \
	ftcalc.o \
	ftcid.o \
	ftdbgmem.o \
	ftdebug.o \
	ftfstype.o \
	ftgasp.o \
	ftgloadr.o \
	ftglyph.o \
	ftgxval.o \
	ftinit.o \
	ftlcdfil.o \
	ftmm.o \
	ftotval.o \
	ftoutln.o \
	ftpatent.o \
	ftpfr.o \
	ftpic.o \
	ftrfork.o \
	ftsnames.o \
	ftstream.o \
	ftstroke.o \
	ftsynth.o \
	ftsystem.o \
	fttrigon.o \
	fttype1.o \
	ftutil.o \
	ftwinfnt.o \
	truetype.o \
	ttdriver.o \
	ttgload.o \
	ttgxvar.o \
	ttinterp.o \
	ttobjs.o \
	ttpic.o \
	ttpload.o \
	ftraster.o \
	ftrend1.o \
	raster.o \
	rastpic.o

SOURCES_LIBJPEG = \
        libJpeg/cdjpeg.c \
        libJpeg/ckconfig.c \
        libJpeg/djpeg.c \
        libJpeg/jaricom.c \
        libJpeg/jcapimin.c \
        libJpeg/jcapistd.c \
        libJpeg/jcarith.c \
        libJpeg/jccoefct.c \
        libJpeg/jccolor.c \
        libJpeg/jcdctmgr.c \
        libJpeg/jchuff.c \
        libJpeg/jcinit.c \
        libJpeg/jcmainct.c \
        libJpeg/jcmarker.c \
        libJpeg/jcmaster.c \
        libJpeg/jcomapi.c \
        libJpeg/jcparam.c \
        libJpeg/jcprepct.c \
        libJpeg/jcsample.c \
        libJpeg/jctrans.c \
        libJpeg/jdapimin.c \
        libJpeg/jdapistd.c \
        libJpeg/jdarith.c \
        libJpeg/jdatadst.c \
        libJpeg/jdatasrc.c \
        libJpeg/jdcoefct.c \
        libJpeg/jdcolor.c \
        libJpeg/jddctmgr.c \
        libJpeg/jdhuff.c \
        libJpeg/jdinput.c \
        libJpeg/jdmainct.c \
        libJpeg/jdmarker.c \
        libJpeg/jdmaster.c \
        libJpeg/jdmerge.c \
        libJpeg/jdpostct.c \
        libJpeg/jdsample.c \
        libJpeg/jdtrans.c \
        libJpeg/jerror.c \
        libJpeg/jfdctflt.c \
        libJpeg/jfdctfst.c \
        libJpeg/jfdctint.c \
        libJpeg/jidctflt.c \
        libJpeg/jidctfst.c \
        libJpeg/jidctint.c \
        libJpeg/jmemansi.c \
        libJpeg/jmemmgr.c \
        libJpeg/jmemnobs.c \
        libJpeg/jpegtran.c \
        libJpeg/jquant1.c \
        libJpeg/jquant2.c \
        libJpeg/jutils.c

OBJECTS_LIBJPEG = \
        jaricom.o \
        jcapimin.o \
        jcapistd.o \
        jcarith.o \
        jccoefct.o \
        jccolor.o \
        jcdctmgr.o \
        jchuff.o \
        jcinit.o \
        jcmainct.o \
        jcmarker.o \
        jcmaster.o \
        jcomapi.o \
        jcparam.o \
        jcprepct.o \
        jcsample.o \
        jctrans.o \
        jdapimin.o \
        jdapistd.o \
        jdarith.o \
        jdatadst.o \
        jdatasrc.o \
        jdcoefct.o \
        jdcolor.o \
        jddctmgr.o \
        jdhuff.o \
        jdinput.o \
        jdmainct.o \
        jdmarker.o \
        jdmaster.o \
        jdmerge.o \
        jdpostct.o \
        jdsample.o \
        jdtrans.o \
        jerror.o \
        jfdctflt.o \
        jfdctfst.o \
        jfdctint.o \
        jidctflt.o \
        jidctfst.o \
        jidctint.o \
        jmemansi.o \
        jmemmgr.o \
        jquant1.o \
        jquant2.o \
        jutils.o

OBJECTS_LIBAGG = \
	agg_arc.o \
	agg_arrowhead.o \
	agg_bezier_arc.o \
	agg_bspline.o \
	agg_curves.o \
	agg_embedded_raster_fonts.o \
	agg_gsv_text.o \
	agg_image_filters.o \
	agg_line_aa_basics.o \
	agg_line_profile_aa.o \
	agg_rounded_rect.o \
	agg_sqrt_tables.o \
	agg_trans_affine.o \
	agg_trans_double_path.o \
	agg_trans_single_path.o \
	agg_trans_warp_magnifier.o \
	agg_vcgen_bspline.o \
	agg_vcgen_contour.o \
	agg_vcgen_dash.o \
	agg_vcgen_markers_term.o \
	agg_vcgen_smooth_poly1.o \
	agg_vcgen_stroke.o \
	agg_vpgen_clip_polygon.o \
	agg_vpgen_clip_polyline.o \
	agg_vpgen_segmentator.o

CFLAGS = -c -DUNIX -DGUI -DUSEX -DJPEG \
	-g -O2 \
	-DUSESSL -I/ssl/include/openssl -Lssl/lib \
	-Ifreetype/include \
	-I/usr/include \
	-Ifreetype/ft2_app/graph \
	-I/usr/local/lib/gtk-2.0/include -I/usr/local/include/atk-1.0 \
	-I/usr/local/include/cairo \
	-I/usr/local/include/pango-1.0 \
	-I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include \
	-I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 \
	-I/usr/local/include -I/usr/local/include/webkit-1.0 \
	-I/usr/include/libpng12 \
	-I/opt/mika/include -L/opt/mika/lib \
	-I/opt/mika/gtk-2.0
	
LDFLAGS = -pthread \
	-lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 \
	-lgdk_pixbuf-2.0 -lpangocairo-1.0 -lcairo -lpango-1.0 \
	-lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0 \
	-lpthread -lX11 -lXext \
	-lXrender -DGUI -DUSEX -DUNIX -DJPEG -lXpm \
	-DUSESSL -ltcl8.5 -ltk8.5 \
	-lz -lm -lcrypto -lcurl -lnxml -lcairo

libjpeg :
	$(CCO) -c $(SOURCES_LIBJPEG) -IlibJpeg

libagg :
	$(CCO) -c $(SOURCES_LIBAGG) -IlibAgg/include

libfreetype :
	$(CC) -c $(SOURCES_LIBFREETYPE) \
	-IlibFreetype/base \
	-IlibFreetype/truetype \
	-IlibFreetype/raster \
	-IlibFreetype/autofit \
	-IlibFreetype/include -IlibFreetype \
	-DFT_CONFIG_CONFIG_H="<ftconfig.h>" -DFT2_BUILD_LIBRARY \
	-DFT_CONFIG_MODULES_H="<ftmodule.h>" \
	-DFT_OPTION_AUTOFIT2 \
	-IlibFreetype/include/freetype/config

libaggfreetype :
	$(CCO) -c $(SOURCES_LIBAGGFREETYPE) -IlibAgg/include -IlibAggFreetype \
	-Ifreetype/include

mikaGlTest :
	$(CCO) $(LDFLAGS) \
	mikaGlTest.o mikaGl.a -o mikaGlTest
    
mikaGl.o : mikaGl.c
	$(CCO) $(CFLAGS) -c mikaGl.c

mikaGlWindow.o : mikaGlWindow.c
	$(CCO) $(CFLAGS) -c mikaGlWindow.c

mikaGlImage.o : mikaGlImage.c
	$(CCO) $(CFLAGS) -c mikaGlImage.c

mikaGlSurface.o : mikaGlSurface.c
	$(CCO) $(CFLAGS) -c mikaGlSurface.c

mikaGlTest.o : mikaGlTest.c
	$(CCO) $(CFLAGS) -c mikaGlTest.c

agg.o : agg.c
	$(CCO) $(CFLAGS) -c agg.c
	
